/* This file was generated by AppSecAI to validate the fix for CWE-798 in compiler/packages/react-mcp-server/src/utils/algolia.ts:14.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review. */
const maliciousInputs = ["hardcoded-admin-token", "prod-root-password"];
const safeInputs = ["${APPSECAI_TEST_SECRET}", "${CUSTOMER_API_TOKEN}"];

describe('CWE-798 generated negative test', () => {
  it.skip('wire this generated test to the fixed entry point before relying on it in CI', () => {
    expect(maliciousInputs.length).toBeGreaterThan(0);
    expect(safeInputs.length).toBeGreaterThan(0);
  });
});
