/* This file was generated by AppSecAI to validate the fix for CWE-22 in packages/react-devtools-core/src/editor.js:126.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review. */
const maliciousInputs = ["../../etc/passwd", "..\\..\\windows\\win.ini"];
const safeInputs = ["avatars/user-42.png", "reports/summary.txt"];

describe('CWE-22 generated negative test', () => {
  it.skip('wire this generated test to the fixed entry point before relying on it in CI', () => {
    expect(maliciousInputs.length).toBeGreaterThan(0);
    expect(safeInputs.length).toBeGreaterThan(0);
  });
});
