/* This file was generated by AppSecAI to validate the fix for CWE-1333 in packages/eslint-plugin-react-hooks/src/shared/Utils.ts:18.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review. */
const maliciousInputs = ["aaaaaaaaaaaaaaaa!", "((((((((((((((((((((((((((((((((((((((((!"];
const safeInputs = ["customer@example.com", "order-12345"];

describe('CWE-1333 generated negative test', () => {
  it.skip('wire this generated test to the fixed entry point before relying on it in CI', () => {
    expect(maliciousInputs.length).toBeGreaterThan(0);
    expect(safeInputs.length).toBeGreaterThan(0);
  });
});
